// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/api/types/events"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDockerAPI creates a new instance of MockDockerAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDockerAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDockerAPI {
	mock := &MockDockerAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDockerAPI is an autogenerated mock type for the dockerAPI type
type MockDockerAPI struct {
	mock.Mock
}

type MockDockerAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDockerAPI) EXPECT() *MockDockerAPI_Expecter {
	return &MockDockerAPI_Expecter{mock: &_m.Mock}
}

// ClientVersion provides a mock function for the type MockDockerAPI
func (_mock *MockDockerAPI) ClientVersion() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClientVersion")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDockerAPI_ClientVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientVersion'
type MockDockerAPI_ClientVersion_Call struct {
	*mock.Call
}

// ClientVersion is a helper method to define mock.On call
func (_e *MockDockerAPI_Expecter) ClientVersion() *MockDockerAPI_ClientVersion_Call {
	return &MockDockerAPI_ClientVersion_Call{Call: _e.mock.On("ClientVersion")}
}

func (_c *MockDockerAPI_ClientVersion_Call) Run(run func()) *MockDockerAPI_ClientVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDockerAPI_ClientVersion_Call) Return(s string) *MockDockerAPI_ClientVersion_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDockerAPI_ClientVersion_Call) RunAndReturn(run func() string) *MockDockerAPI_ClientVersion_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerInspect provides a mock function for the type MockDockerAPI
func (_mock *MockDockerAPI) ContainerInspect(ctx context.Context, containerID string) (container.InspectResponse, error) {
	ret := _mock.Called(ctx, containerID)

	if len(ret) == 0 {
		panic("no return value specified for ContainerInspect")
	}

	var r0 container.InspectResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (container.InspectResponse, error)); ok {
		return returnFunc(ctx, containerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) container.InspectResponse); ok {
		r0 = returnFunc(ctx, containerID)
	} else {
		r0 = ret.Get(0).(container.InspectResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, containerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDockerAPI_ContainerInspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerInspect'
type MockDockerAPI_ContainerInspect_Call struct {
	*mock.Call
}

// ContainerInspect is a helper method to define mock.On call
//   - ctx context.Context
//   - containerID string
func (_e *MockDockerAPI_Expecter) ContainerInspect(ctx interface{}, containerID interface{}) *MockDockerAPI_ContainerInspect_Call {
	return &MockDockerAPI_ContainerInspect_Call{Call: _e.mock.On("ContainerInspect", ctx, containerID)}
}

func (_c *MockDockerAPI_ContainerInspect_Call) Run(run func(ctx context.Context, containerID string)) *MockDockerAPI_ContainerInspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDockerAPI_ContainerInspect_Call) Return(inspectResponse container.InspectResponse, err error) *MockDockerAPI_ContainerInspect_Call {
	_c.Call.Return(inspectResponse, err)
	return _c
}

func (_c *MockDockerAPI_ContainerInspect_Call) RunAndReturn(run func(ctx context.Context, containerID string) (container.InspectResponse, error)) *MockDockerAPI_ContainerInspect_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerList provides a mock function for the type MockDockerAPI
func (_mock *MockDockerAPI) ContainerList(ctx context.Context, options container.ListOptions) ([]container.Summary, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for ContainerList")
	}

	var r0 []container.Summary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, container.ListOptions) ([]container.Summary, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, container.ListOptions) []container.Summary); ok {
		r0 = returnFunc(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]container.Summary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, container.ListOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDockerAPI_ContainerList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerList'
type MockDockerAPI_ContainerList_Call struct {
	*mock.Call
}

// ContainerList is a helper method to define mock.On call
//   - ctx context.Context
//   - options container.ListOptions
func (_e *MockDockerAPI_Expecter) ContainerList(ctx interface{}, options interface{}) *MockDockerAPI_ContainerList_Call {
	return &MockDockerAPI_ContainerList_Call{Call: _e.mock.On("ContainerList", ctx, options)}
}

func (_c *MockDockerAPI_ContainerList_Call) Run(run func(ctx context.Context, options container.ListOptions)) *MockDockerAPI_ContainerList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 container.ListOptions
		if args[1] != nil {
			arg1 = args[1].(container.ListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDockerAPI_ContainerList_Call) Return(summarys []container.Summary, err error) *MockDockerAPI_ContainerList_Call {
	_c.Call.Return(summarys, err)
	return _c
}

func (_c *MockDockerAPI_ContainerList_Call) RunAndReturn(run func(ctx context.Context, options container.ListOptions) ([]container.Summary, error)) *MockDockerAPI_ContainerList_Call {
	_c.Call.Return(run)
	return _c
}

// DaemonHost provides a mock function for the type MockDockerAPI
func (_mock *MockDockerAPI) DaemonHost() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DaemonHost")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDockerAPI_DaemonHost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DaemonHost'
type MockDockerAPI_DaemonHost_Call struct {
	*mock.Call
}

// DaemonHost is a helper method to define mock.On call
func (_e *MockDockerAPI_Expecter) DaemonHost() *MockDockerAPI_DaemonHost_Call {
	return &MockDockerAPI_DaemonHost_Call{Call: _e.mock.On("DaemonHost")}
}

func (_c *MockDockerAPI_DaemonHost_Call) Run(run func()) *MockDockerAPI_DaemonHost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDockerAPI_DaemonHost_Call) Return(s string) *MockDockerAPI_DaemonHost_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDockerAPI_DaemonHost_Call) RunAndReturn(run func() string) *MockDockerAPI_DaemonHost_Call {
	_c.Call.Return(run)
	return _c
}

// Events provides a mock function for the type MockDockerAPI
func (_mock *MockDockerAPI) Events(ctx context.Context, options events.ListOptions) (<-chan events.Message, <-chan error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for Events")
	}

	var r0 <-chan events.Message
	var r1 <-chan error
	if returnFunc, ok := ret.Get(0).(func(context.Context, events.ListOptions) (<-chan events.Message, <-chan error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, events.ListOptions) <-chan events.Message); ok {
		r0 = returnFunc(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan events.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, events.ListOptions) <-chan error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}
	return r0, r1
}

// MockDockerAPI_Events_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Events'
type MockDockerAPI_Events_Call struct {
	*mock.Call
}

// Events is a helper method to define mock.On call
//   - ctx context.Context
//   - options events.ListOptions
func (_e *MockDockerAPI_Expecter) Events(ctx interface{}, options interface{}) *MockDockerAPI_Events_Call {
	return &MockDockerAPI_Events_Call{Call: _e.mock.On("Events", ctx, options)}
}

func (_c *MockDockerAPI_Events_Call) Run(run func(ctx context.Context, options events.ListOptions)) *MockDockerAPI_Events_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 events.ListOptions
		if args[1] != nil {
			arg1 = args[1].(events.ListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDockerAPI_Events_Call) Return(messageCh <-chan events.Message, errCh <-chan error) *MockDockerAPI_Events_Call {
	_c.Call.Return(messageCh, errCh)
	return _c
}

func (_c *MockDockerAPI_Events_Call) RunAndReturn(run func(ctx context.Context, options events.ListOptions) (<-chan events.Message, <-chan error)) *MockDockerAPI_Events_Call {
	_c.Call.Return(run)
	return _c
}
