// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIPDetector creates a new instance of MockIPDetector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPDetector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPDetector {
	mock := &MockIPDetector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPDetector is an autogenerated mock type for the ipDetector type
type MockIPDetector struct {
	mock.Mock
}

type MockIPDetector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPDetector) EXPECT() *MockIPDetector_Expecter {
	return &MockIPDetector_Expecter{mock: &_m.Mock}
}

// GetAddresses provides a mock function for the type MockIPDetector
func (_mock *MockIPDetector) GetAddresses(p net.Interface) ([]net.Addr, error) {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for GetAddresses")
	}

	var r0 []net.Addr
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(net.Interface) ([]net.Addr, error)); ok {
		return returnFunc(p)
	}
	if returnFunc, ok := ret.Get(0).(func(net.Interface) []net.Addr); ok {
		r0 = returnFunc(p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.Addr)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(net.Interface) error); ok {
		r1 = returnFunc(p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPDetector_GetAddresses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAddresses'
type MockIPDetector_GetAddresses_Call struct {
	*mock.Call
}

// GetAddresses is a helper method to define mock.On call
//   - p net.Interface
func (_e *MockIPDetector_Expecter) GetAddresses(p interface{}) *MockIPDetector_GetAddresses_Call {
	return &MockIPDetector_GetAddresses_Call{Call: _e.mock.On("GetAddresses", p)}
}

func (_c *MockIPDetector_GetAddresses_Call) Run(run func(p net.Interface)) *MockIPDetector_GetAddresses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 net.Interface
		if args[0] != nil {
			arg0 = args[0].(net.Interface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPDetector_GetAddresses_Call) Return(addrs []net.Addr, err error) *MockIPDetector_GetAddresses_Call {
	_c.Call.Return(addrs, err)
	return _c
}

func (_c *MockIPDetector_GetAddresses_Call) RunAndReturn(run func(p net.Interface) ([]net.Addr, error)) *MockIPDetector_GetAddresses_Call {
	_c.Call.Return(run)
	return _c
}

// GetInterfaces provides a mock function for the type MockIPDetector
func (_mock *MockIPDetector) GetInterfaces() ([]net.Interface, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInterfaces")
	}

	var r0 []net.Interface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]net.Interface, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []net.Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.Interface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPDetector_GetInterfaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInterfaces'
type MockIPDetector_GetInterfaces_Call struct {
	*mock.Call
}

// GetInterfaces is a helper method to define mock.On call
func (_e *MockIPDetector_Expecter) GetInterfaces() *MockIPDetector_GetInterfaces_Call {
	return &MockIPDetector_GetInterfaces_Call{Call: _e.mock.On("GetInterfaces")}
}

func (_c *MockIPDetector_GetInterfaces_Call) Run(run func()) *MockIPDetector_GetInterfaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPDetector_GetInterfaces_Call) Return(interfaces []net.Interface, err error) *MockIPDetector_GetInterfaces_Call {
	_c.Call.Return(interfaces, err)
	return _c
}

func (_c *MockIPDetector_GetInterfaces_Call) RunAndReturn(run func() ([]net.Interface, error)) *MockIPDetector_GetInterfaces_Call {
	_c.Call.Return(run)
	return _c
}
