// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/docker/docker/api/types/container"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFTUEDockerAPI creates a new instance of MockFTUEDockerAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFTUEDockerAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFTUEDockerAPI {
	mock := &MockFTUEDockerAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFTUEDockerAPI is an autogenerated mock type for the dockerAPI type
type MockFTUEDockerAPI struct {
	mock.Mock
}

type MockFTUEDockerAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFTUEDockerAPI) EXPECT() *MockFTUEDockerAPI_Expecter {
	return &MockFTUEDockerAPI_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockFTUEDockerAPI
func (_mock *MockFTUEDockerAPI) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFTUEDockerAPI_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockFTUEDockerAPI_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockFTUEDockerAPI_Expecter) Close() *MockFTUEDockerAPI_Close_Call {
	return &MockFTUEDockerAPI_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockFTUEDockerAPI_Close_Call) Run(run func()) *MockFTUEDockerAPI_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFTUEDockerAPI_Close_Call) Return(err error) *MockFTUEDockerAPI_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFTUEDockerAPI_Close_Call) RunAndReturn(run func() error) *MockFTUEDockerAPI_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ContainerList provides a mock function for the type MockFTUEDockerAPI
func (_mock *MockFTUEDockerAPI) ContainerList(context1 context.Context, listOptions container.ListOptions) ([]container.Summary, error) {
	ret := _mock.Called(context1, listOptions)

	if len(ret) == 0 {
		panic("no return value specified for ContainerList")
	}

	var r0 []container.Summary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, container.ListOptions) ([]container.Summary, error)); ok {
		return returnFunc(context1, listOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, container.ListOptions) []container.Summary); ok {
		r0 = returnFunc(context1, listOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]container.Summary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, container.ListOptions) error); ok {
		r1 = returnFunc(context1, listOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFTUEDockerAPI_ContainerList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerList'
type MockFTUEDockerAPI_ContainerList_Call struct {
	*mock.Call
}

// ContainerList is a helper method to define mock.On call
//   - context1 context.Context
//   - listOptions container.ListOptions
func (_e *MockFTUEDockerAPI_Expecter) ContainerList(context1 interface{}, listOptions interface{}) *MockFTUEDockerAPI_ContainerList_Call {
	return &MockFTUEDockerAPI_ContainerList_Call{Call: _e.mock.On("ContainerList", context1, listOptions)}
}

func (_c *MockFTUEDockerAPI_ContainerList_Call) Run(run func(context1 context.Context, listOptions container.ListOptions)) *MockFTUEDockerAPI_ContainerList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 container.ListOptions
		if args[1] != nil {
			arg1 = args[1].(container.ListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFTUEDockerAPI_ContainerList_Call) Return(summarys []container.Summary, err error) *MockFTUEDockerAPI_ContainerList_Call {
	_c.Call.Return(summarys, err)
	return _c
}

func (_c *MockFTUEDockerAPI_ContainerList_Call) RunAndReturn(run func(context1 context.Context, listOptions container.ListOptions) ([]container.Summary, error)) *MockFTUEDockerAPI_ContainerList_Call {
	_c.Call.Return(run)
	return _c
}
