// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPasswordValidatorError creates a new instance of MockPasswordValidatorError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordValidatorError(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordValidatorError {
	mock := &MockPasswordValidatorError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordValidatorError is an autogenerated mock type for the PasswordValidatorError type
type MockPasswordValidatorError struct {
	mock.Mock
}

type MockPasswordValidatorError_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordValidatorError) EXPECT() *MockPasswordValidatorError_Expecter {
	return &MockPasswordValidatorError_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type MockPasswordValidatorError
func (_mock *MockPasswordValidatorError) Error() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPasswordValidatorError_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockPasswordValidatorError_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *MockPasswordValidatorError_Expecter) Error() *MockPasswordValidatorError_Error_Call {
	return &MockPasswordValidatorError_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *MockPasswordValidatorError_Error_Call) Run(run func()) *MockPasswordValidatorError_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPasswordValidatorError_Error_Call) Return(s string) *MockPasswordValidatorError_Error_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPasswordValidatorError_Error_Call) RunAndReturn(run func() string) *MockPasswordValidatorError_Error_Call {
	_c.Call.Return(run)
	return _c
}

// isAuthError provides a mock function for the type MockPasswordValidatorError
func (_mock *MockPasswordValidatorError) isAuthError() {
	_mock.Called()
	return
}

// MockPasswordValidatorError_isAuthError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isAuthError'
type MockPasswordValidatorError_isAuthError_Call struct {
	*mock.Call
}

// isAuthError is a helper method to define mock.On call
func (_e *MockPasswordValidatorError_Expecter) isAuthError() *MockPasswordValidatorError_isAuthError_Call {
	return &MockPasswordValidatorError_isAuthError_Call{Call: _e.mock.On("isAuthError")}
}

func (_c *MockPasswordValidatorError_isAuthError_Call) Run(run func()) *MockPasswordValidatorError_isAuthError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPasswordValidatorError_isAuthError_Call) Return() *MockPasswordValidatorError_isAuthError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPasswordValidatorError_isAuthError_Call) RunAndReturn(run func()) *MockPasswordValidatorError_isAuthError_Call {
	_c.Run(run)
	return _c
}
