// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/lthummus/auththingie2/internal/user"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPasswordValidator creates a new instance of MockPasswordValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordValidator {
	mock := &MockPasswordValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordValidator is an autogenerated mock type for the PasswordValidator type
type MockPasswordValidator struct {
	mock.Mock
}

type MockPasswordValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordValidator) EXPECT() *MockPasswordValidator_Expecter {
	return &MockPasswordValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type MockPasswordValidator
func (_mock *MockPasswordValidator) Validate(ctx context.Context, username string, password string, sourceIP string) (*user.User, error) {
	ret := _mock.Called(ctx, username, password, sourceIP)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*user.User, error)); ok {
		return returnFunc(ctx, username, password, sourceIP)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *user.User); ok {
		r0 = returnFunc(ctx, username, password, sourceIP)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, username, password, sourceIP)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasswordValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockPasswordValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
//   - sourceIP string
func (_e *MockPasswordValidator_Expecter) Validate(ctx interface{}, username interface{}, password interface{}, sourceIP interface{}) *MockPasswordValidator_Validate_Call {
	return &MockPasswordValidator_Validate_Call{Call: _e.mock.On("Validate", ctx, username, password, sourceIP)}
}

func (_c *MockPasswordValidator_Validate_Call) Run(run func(ctx context.Context, username string, password string, sourceIP string)) *MockPasswordValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPasswordValidator_Validate_Call) Return(user1 *user.User, err error) *MockPasswordValidator_Validate_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockPasswordValidator_Validate_Call) RunAndReturn(run func(ctx context.Context, username string, password string, sourceIP string) (*user.User, error)) *MockPasswordValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}
