// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRedirectURIValidator creates a new instance of MockRedirectURIValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedirectURIValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedirectURIValidator {
	mock := &MockRedirectURIValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRedirectURIValidator is an autogenerated mock type for the Validator type
type MockRedirectURIValidator struct {
	mock.Mock
}

type MockRedirectURIValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedirectURIValidator) EXPECT() *MockRedirectURIValidator_Expecter {
	return &MockRedirectURIValidator_Expecter{mock: &_m.Mock}
}

// IsAllowed provides a mock function for the type MockRedirectURIValidator
func (_mock *MockRedirectURIValidator) IsAllowed(rawURL string) bool {
	ret := _mock.Called(rawURL)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowed")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(rawURL)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockRedirectURIValidator_IsAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAllowed'
type MockRedirectURIValidator_IsAllowed_Call struct {
	*mock.Call
}

// IsAllowed is a helper method to define mock.On call
//   - rawURL string
func (_e *MockRedirectURIValidator_Expecter) IsAllowed(rawURL interface{}) *MockRedirectURIValidator_IsAllowed_Call {
	return &MockRedirectURIValidator_IsAllowed_Call{Call: _e.mock.On("IsAllowed", rawURL)}
}

func (_c *MockRedirectURIValidator_IsAllowed_Call) Run(run func(rawURL string)) *MockRedirectURIValidator_IsAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRedirectURIValidator_IsAllowed_Call) Return(b bool) *MockRedirectURIValidator_IsAllowed_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockRedirectURIValidator_IsAllowed_Call) RunAndReturn(run func(rawURL string) bool) *MockRedirectURIValidator_IsAllowed_Call {
	_c.Call.Return(run)
	return _c
}

// Sanitize provides a mock function for the type MockRedirectURIValidator
func (_mock *MockRedirectURIValidator) Sanitize(rawURL string) (string, bool) {
	ret := _mock.Called(rawURL)

	if len(ret) == 0 {
		panic("no return value specified for Sanitize")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return returnFunc(rawURL)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(rawURL)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(rawURL)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockRedirectURIValidator_Sanitize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sanitize'
type MockRedirectURIValidator_Sanitize_Call struct {
	*mock.Call
}

// Sanitize is a helper method to define mock.On call
//   - rawURL string
func (_e *MockRedirectURIValidator_Expecter) Sanitize(rawURL interface{}) *MockRedirectURIValidator_Sanitize_Call {
	return &MockRedirectURIValidator_Sanitize_Call{Call: _e.mock.On("Sanitize", rawURL)}
}

func (_c *MockRedirectURIValidator_Sanitize_Call) Run(run func(rawURL string)) *MockRedirectURIValidator_Sanitize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRedirectURIValidator_Sanitize_Call) Return(s string, b bool) *MockRedirectURIValidator_Sanitize_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *MockRedirectURIValidator_Sanitize_Call) RunAndReturn(run func(rawURL string) (string, bool)) *MockRedirectURIValidator_Sanitize_Call {
	_c.Call.Return(run)
	return _c
}
