all: false
dir: internal/mocks
filename: "{{.InterfaceName}}.go"
pkgname: "mocks"
template: testify
packages:
  github.com/lthummus/auththingie2/internal/db:
    config:
      all: true
  github.com/lthummus/auththingie2/internal/rules:
    config:
      all: true
  github.com/lthummus/auththingie2/internal/loginlimit:
    config:
      all: true
