// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ContainsID is an autogenerated mock type for the ContainsID type
type ContainsID struct {
	mock.Mock
}

// ID provides a mock function with given fields:
func (_m *ContainsID) ID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewContainsID creates a new instance of ContainsID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContainsID(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContainsID {
	mock := &ContainsID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
