name: ci

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Install dependencies
        run: go get .

      - name: Compile
        run: go build -v ./...

      - name: Run Tests
        run: go run gotest.tools/gotestsum@latest --format github-actions


